'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _webgl = require('../../../webgl.js');

var Locations = function Locations(gl, program) {

  /**
   * @type {WebGLUniformLocation}
   */
  this.u_texCoordMatrix = gl.getUniformLocation(program, _webgl.DEBUG ? 'u_texCoordMatrix' : 'd');

  /**
   * @type {WebGLUniformLocation}
   */
  this.u_projectionMatrix = gl.getUniformLocation(program, _webgl.DEBUG ? 'u_projectionMatrix' : 'e');

  /**
   * @type {WebGLUniformLocation}
   */
  this.u_opacity = gl.getUniformLocation(program, _webgl.DEBUG ? 'u_opacity' : 'f');

  /**
   * @type {WebGLUniformLocation}
   */
  this.u_texture = gl.getUniformLocation(program, _webgl.DEBUG ? 'u_texture' : 'g');

  /**
   * @type {number}
   */
  this.a_position = gl.getAttribLocation(program, _webgl.DEBUG ? 'a_position' : 'b');

  /**
   * @type {number}
   */
  this.a_texCoord = gl.getAttribLocation(program, _webgl.DEBUG ? 'a_texCoord' : 'c');
}; /**
    * @module ol/renderer/webgl/defaultmapshader/Locations
    */
// This file is automatically generated, do not edit
// Run `make shaders` to generate, and commit the result.

exports.default = Locations;

//# sourceMappingURL=Locations.js.map